openapi: 3.0.0
info:
    version: 1.0.0
    description: API to obtain Calendar files from VIT timetable website data
    title: VIT Calendar API
    contact:
        name: Sankalp Mukim
        url: github.com/sankalpmukim
        email: sankalpmukim@gmail.com
servers:
-   url: https://vitcalapi.herokuapp.com
    description: Simple FLASK application
paths:
    /vellore:
        post:
            summary: 'Returns exact contents writeable to a .ics file for vellore'
            description: >
                Obtain the data of full page of VTOP(Vellore Campus) timetable page
                Make sure the new lines are separated be \r\n Only
            tags:
                - json
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Input'
                        example:
                            timetable: '\r\n'
            responses:
                '200':
                    description: 'timetable object returned succesfully'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Output'
                            example:
                                "reg_no": "20BDS0128"
                                "calendar": "abcd"
components:
    schemas:
        Output:
            type: object
            properties:
                reg_no:
                    type: string
                calendar:
                    type: string
        Input:
            type: object
            properties:
                timetable:
                    type: string
            required:
                - timetable
